### ISSUE TITLE
Build Error IOWrapper

### ISSUE THREAD

**Issue by hanskumarKEF** [lukasvst/dm-vio-ros#1]
Hi,
When running catkin_make, I come upon the following error. Was wondering where this file was located and if I forgot to link it properly?

fatal error: IOWrapper/Output3DWrapper.h: No such file or directory
 #include "IOWrapper/Output3DWrapper.h"

**Comment by lukasvst** [comment]
This file is in the main DM-VIO project https://github.com/lukasvst/dm-vio/tree/master/src/dso/IOWrapper and should be in the include directories.
What is the value of DMVIO_BUILD (e.g. run `echo $DMVIO_BUILD` in the terminal)?
It needs to be a direct subfolder of the location you cloned DM-VIO in (e.g. /home/user/dm-vio/cmake-build-relwithdebinfo)

**Comment by hanskumarKEF** [comment]
Thanks for quick reply. 

I had an error in the name of this build folder that I was able to resolve. Still running into an issue building the ros wrapper, however. 

![image](https://user-images.githubusercontent.com/84034448/177852945-b3f82870-5fbd-4657-bbcd-8a62bf744bcc.png)

**Comment by lukasvst** [comment]
Interesting, I haven't seen this error before.
Maybe can you try adding the following line to https://github.com/lukasvst/dm-vio/blob/master/CMakeLists.txt#L42
`set(CMAKE_POSITION_INDEPENDENT_CODE ON)`
and then recompile everything?

Alternatively, you could try changing this line https://github.com/lukasvst/dm-vio/blob/master/CMakeLists.txt#L47 to 
`    "${SSE_FLAGS} -fPIC"`

Otherwise, can you let me know your OS and ROS version?
And do normal DM-VIO, and other ROS packages work?

**Comment by hanskumarKEF** [comment]
When I changed this line https://github.com/lukasvst/dm-vio/blob/master/CMakeLists.txt#L47 to
"${SSE_FLAGS} -fPIC" everything compiles and runs great! Thank you!

**Comment by shockwaveHe** [comment]
Hi @lukasvst, I also get the error of IOWrapper. Here is my DMVIO_BUILD value:  `/home/yao/MSO_compare_alg/DM-VIO/dm-vio/build`. Is there something else I need to config? Thanks!

**Comment by lukasvst** [comment]
Usually there is nothing else you need to configure, other than the instructions in the readme.
Are you sure that the DMVIO_BUILD value is available to the cmake script (i.e. does it print out "Path to DM-VIO build folder is: ...") and that the path is correct?

**Comment by shockwaveHe** [comment]
@lukasvst I delete the devel and build folder and rebuild the stack. It works now. I guess there was cache error before. Thank you!

**Comment by ForLoveandPeace** [comment]
Hi, Thanks for your great work! 
I met the same error as above on Jetson AGX Orin with JetPack 5.3. The OS is Ubuntu 20.04. 
I did this `set(CMAKE_POSITION_INDEPENDENT_CODE ON)`, but it didn't work. (fatal error: IOWrapper/Output3DWrapper.h: No such file or directory at the dm-vio-ros compilation)
After I added -fPIC in CMakeLists.txt, it encountered a error(-fPIC: not found) at the dm-vio compilation.
Could you help me?
