### ISSUE TITLE
package dmvio_ros  not found

### ISSUE THREAD

**Issue by hee18** [lukasvst/dm-vio-ros#17]
Hello, I have an issue and difficult to solve it.
I downloaded and built DM-VIO successfully. I also confirmed running with python tool. I wanted to run my own dataset which is .bag file, so tried to use dm-vio roswrapper. However, I can't find dmvio_ros package. 'rosrun dmvio_ros node' did not work. I already set DMVIO_BUILD path to /home/user/catkin_ws/dm-vio/cmake-build-relwithdebinfo. What's the problem? How can I solve this?

I tried delete&rebuild DM-VIO, too. 
I look forward to answer from you, thankyou!

**Comment by lukasvst** [comment]
Thanks for first verifying with the python tools.

Have you sourced your ROS workspace ( `source your_workspace/devel/setup.bash` ), ideally in your `.bashrc`?

I assume that building the ros driver with catkin_make was successful?

**Comment by hee18** [comment]
Yeah, I did it. Can you explain me about "export DMVIO_BUILD=/PATH/TO/dm-vio/cmake-build-relwithdebinfo" in detail? Especially about cmake-build-relwithdebinfo plz. Do I have to make folder named "cmake-build-relwithdebinfo"?

**Comment by lukasvst** [comment]
cmake-build-relwithdebinfo is just the name of the build folder. It's the default name when using CLion, but you can also call it `build` instead.
The important part is that you need to have DM-VIO built in this folder (i.e. that's where you ran `cmake ..` and make).

But I don't think `catkin_make`will run successfully unless you have set this correctly.

**Comment by hee18** [comment]
Yes, It was my simple mistake. I solved it. Thanks for your kind response!
