### ISSUE TITLE
Question on running own datasets in rosbag format

### ISSUE THREAD

**Issue by wwtinwhu** [lukasvst/dm-vio-ros#2]
Hello, @lukasvst !  I read the tips in the dm-vio pages for Running on your own datasets.  Does the same apply to the Rosbag format?  For example: For each image it must contain an IMU 'measurement' with exactly the same timestamp.  Thanks!

**Comment by lukasvst** [comment]
When running with ROS you do not need an IMU measurement with the same timestamp as images. These will be automatically interpolated by the ROS wrapper.

The other points (camera calibration, IMU calibration) in the page "Running on your own datasets" can still be useful, but the points regarding `files=...`, the `times.txt`-file and the imu file don't apply as this information is taken from ROS topics.

**Comment by wwtinwhu** [comment]
Thanks @lukasvst . I met another problem. When the imuCalib para is set, the terminal output the error: 

"Loading IMU parameter file at: /xxx/dm_vio_setting/imu_noise.yaml
terminate called after throwing an instance of 'YAML::TypedBadConversion<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > >'
  what():  yaml-cpp: error at line 0, column 0: bad conversion"

However, the imu_noise.yaml's format is same as the euroc.yaml. Thanks

**Comment by wwtinwhu** [comment]
> When running with ROS you do not need an IMU measurement with the same timestamp as images. These will be automatically interpolated by the ROS wrapper.
> 
> The other points (camera calibration, IMU calibration) in the page "Running on your own datasets" can still be useful, but the points regarding `files=...`, the `times.txt`-file and the imu file don't apply as this information is taken from ROS topics.

When I run my own rosbag data, the terminal output this:
WARNING: Not sending frame, because it does not have IMU data yet.
So I check the code in IMUInteropolator.cpp  https://github.com/lukasvst/dm-vio/blob/432b7af3ad35daff804a99175bc0498da4595130/src/live/IMUInterpolator.cpp#L280. So the rosbag data also need an imu timestamp with the same time as images. May I ask where I have not set it? @lukasvst

**Comment by lukasvst** [comment]
This warning you get should only be printed when no IMU data for the frame has been received yet. Are you sure that the ROS driver listens for IMU data on the correct topic and that it has timestamps (in the same time frame as the image timestamps)?
You can put a print out here to see if it actually gets called: https://github.com/lukasvst/dm-vio-ros/blob/master/src/main.cpp#L220

(The IMU data with the same timestamp needed in IMUInterpolator#L280 will be generated / interpolated automatically by the IMUInterpolator once IMU data is received, you do not need to do this yourself).

**Comment by wwtinwhu** [comment]
> This warning you get should only be printed when no IMU data for the frame has been received yet. Are you sure that the ROS driver listens for IMU data on the correct topic and that it has timestamps (in the same time frame as the image timestamps)? You can put a print out here to see if it actually gets called: https://github.com/lukasvst/dm-vio-ros/blob/master/src/main.cpp#L220
> 
> (The IMU data with the same timestamp needed in IMUInterpolator#L280 will be generated / interpolated automatically by the IMUInterpolator once IMU data is received, you do not need to do this yourself).

Hello, @lukasvst . It actually receive the IMU data(I put a print), or it will not call the funciton addGyrData() and trySendingImages().  However , I don't find the code for the interpolated code for imu timestamp. Could you show me where it is? Thanks.

**Comment by wwtinwhu** [comment]
> This warning you get should only be printed when no IMU data for the frame has been received yet. Are you sure that the ROS driver listens for IMU data on the correct topic and that it has timestamps (in the same time frame as the image timestamps)? You can put a print out here to see if it actually gets called: https://github.com/lukasvst/dm-vio-ros/blob/master/src/main.cpp#L220
> 
> (The IMU data with the same timestamp needed in IMUInterpolator#L280 will be generated / interpolated automatically by the IMUInterpolator once IMU data is received, you do not need to do this yourself).

Thanks, @lukasvst . I find the problem. Due to the transmission delay of camera,  image data  is store behind the imu data (which close to the image in time) in rosbag. So I modify the `maxIMUQueueSize`  to wait the image data as my IMU frenquency is relatively high.
https://github.com/lukasvst/dm-vio/blob/432b7af3ad35daff804a99175bc0498da4595130/src/live/IMUInterpolator.h#L124

**Comment by wwtinwhu** [comment]
@lukasvst Hello, I met problem in Initilization. Here is the important output：
By the way,  image size tested is 2000+ x 1500+ , so the fps is around 2Hz. Is there a way to increase the speed?

SKIPPING 0 FRAMES! frames remaining in queue: 58
Scaling with rescaleFactor: 1.41338
Initialization: keep 1.1% (need 1000, have 94240)!
INITIALIZE FROM INITIALIZER (1045 pts)!
Frame history size: 8
Preparing keyframe: 7
Current mapping id: 7 create KF after: 7
Frames between KFs: 6
SPARSITY:  MinActDist 2.100000 (need 1000 points, have 1045 points)!
OPTIMIZE 1045 pts, 1045 active res, 0 lin res!
Initial Error       	A(459389.228531)=(AV inf). Num: A(0) + M(0); ab 0.000000 0.000000!
Dynamic weight: 0
STEPS: A 0.0; B 0.0; R 0.0; T 0.0. 	REJECT 0 (L -5.00, dir nan, ss 1.0): 	A(3591387.825691)=(AV 253.243). Num: A(7) + M(0); ab 0.000000 0.000000!
Dynamic weight: 0.000997792
STEPS: A 1.0; B 2.6; R 31.4; T 69.4. 	REJECT 1 (L -3.00, dir -0.05, ss 1.0): A(3597699.713478)=(AV 253.465). Num: A(7) + M(0); ab 0.008275 -0.220591!
Dynamic weight: 0.000997792
STEPS: A 0.4; B 4.0; R 2.3; T 5.5. 	REJECT 2 (L -1.00, dir 0.19, ss 1.0): A(3595700.639107)=(AV 253.395). Num: A(7) + M(0); ab -0.003426 0.343360!
Dynamic weight: 0.000997792
STEPS: A 0.0; B 0.2; R 0.2; T 0.1. 	ACCEPT 3 (L 1.00, dir 0.80, ss 1.0): 	A(3586891.104179)=(AV 253.084). Num: A(7) + M(0); ab -0.000215 0.015499!
Num BA Iterations done: 4
I THINK INITIALIZATINO FAILED! Resetting.
LOG 7: 253.084 fine. Res: 7 A, 0 L, 0 M; (0 / 0) forceDrop. a=-0.000215, b=0.015499. Window 7 (2)
RESETTING!
destroyed ThreadReduce
Switching to initializer state: RealtimeCoarseIMUInitState

**Comment by lukasvst** [comment]
I'm glad that you found the issue with the queue size!

This was just a failure of the visual initializer (no IMU data involved yet). Is it able to initialize successfully on other sequences (with slow and mostly translational movement)? Otherwise, this would suggest there is a problem with camera calibration.

Your image size is quite large, reducing it will make the system much faster and should have almost not impact on accuracy. I think you should be able to just adjust the output image size in the camera.txt file.
One thing to note is that the visual initializer is still the same as in DSO, so it's expected to be slower than realtime, but after initialization the system should catch up quickly.

**Comment by wwtinwhu** [comment]
> I'm glad that you found the issue with the queue size!
> 
> This was just a failure of the visual initializer (no IMU data involved yet). Is it able to initialize successfully on other sequences (with slow and mostly translational movement)? Otherwise, this would suggest there is a problem with camera calibration.
> 
> Your image size is quite large, reducing it will make the system much faster and should have almost not impact on accuracy. I think you should be able to just adjust the output image size in the camera.txt file. One thing to note is that the visual initializer is still the same as in DSO, so it's expected to be slower than realtime, but after initialization the system should catch up quickly.

Thanks, @lukasvst.  I tried other sequences. There are a few cases that the system don't fail on the initializer. Map points are shown in the viewer. So camera calibration problem is excluded. However, I found that the CoarseIMUInit normalized error is quite large in the terminal. In this sequnence, the program switch to RealtimePGBAState with "CoarseIMUInit normalized error: 701.343 variance: 0.073787 scale: 21.5081" after a few seconds.  What does CoarseIMUInit normalized error mean? And based on my test, it failed initialization in most cases with slow and mostly translational movement.  Is this due to insufficient acceleration? Third, I found in some cases, the tracking point get fewer, however the movement is just walk forward, no big rotation. what is the reason for this？ Thank you.

**Comment by lukasvst** [comment]
Yes, this is quite large. The CoarseIMUInit normalized error is the error in the IMU-initialization graph after optimization and  should be below 1 usually.
If the visual tracking was fine but this error is very large this is usually either:
* The IMU noise values are too large. Are you using the provided [t265_noise_tumvi.yaml](https://github.com/lukasvst/dm-vio/blob/master/configs/t265_noise_tumvi.yaml)?
* Your IMU-camera calibration (camchain.yaml) is wrong.
* There is an uncalibrated time offset between camera and IMU.
* ... some other problem with the IMU data.

The other problems you describe might also come from the same issue, I would suggest to first address it. You can also try to pass `useimu=0` to make sure that the visual-only system works fine.

**Comment by wwtinwhu** [comment]
> Yes, this is quite large. The CoarseIMUInit normalized error is the error in the IMU-initialization graph after optimization and should be below 1 usually. If the visual tracking was fine but this error is very large this is usually either:
> 
> * The IMU noise values are too small. Are you using the provided [t265_noise_tumvi.yaml](https://github.com/lukasvst/dm-vio/blob/master/configs/t265_noise_tumvi.yaml)?
> * Your IMU-camera calibration (camchain.yaml) is wrong.
> * There is an uncalibrated time offset between camera and IMU.
> * ... some other problem with the IMU data.
> 
> The other problems you describe might also come from the same issue, I would suggest to first address it. You can also try to pass `useimu=0` to make sure that the visual-only system works fine.

Thanks, @lukasvst . Your suggestion is very useful！Thanks again for your patient answer！ Looking forward to having the opportunity to cooperate with you on slam in the future.
