### ISSUE TITLE
cmake-build-relwithdebinfo not found

### ISSUE THREAD

**Issue by cmakelabs** [lukasvst/dm-vio-ros#20]
I have followed the instructions carefully, and with the typical `ros_ws` structure I have also cloned the original `dm_vio` in the `src` folder,  with export `DMVIO_BUILD=/home/DM_VIO_ws/src/dm-vio/cmake-build-relwithdebinfo` being in `~/.bashrc` and sourced. However when I cloned the repo for `dm-vio-ros` and tried to build I got:
```

---- Path to DM-VIO build folder is: /home/nuc/DM_VIO_ws/src/dm-vio/cmake-build-relwithdebinfo

-- dmvio_ros: 1 messages, 0 services
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
DMVIO_LIBRARY
    linked by target "dmvio_ros_node" in directory /home/DM_VIO_ws/src/dm-vio-ros
```
Also when I simply check the files in the original `dm_vio`, I do not see anything like `cmake-build-relwithdebinfo`

I would be grateful if you can clarify to me what is the issue here

**Comment by lukasvst** [comment]
You first need to build dm_vio, `cmake-build-relwithdebuinfo` is the name of the build folder you need to create and build it in (you can also call it `build` instead.

So inside dm-vio, run 
```
mkdir build
cd build
cmake ..
make -j
```

And before building dm-vio-ros run
`export DMVIO_BUILD=/home/DM_VIO_ws/src/dm-vio/build`

**Comment by cmakelabs** [comment]
Thanks, it works
