### ISSUE TITLE
Inconvenient borrowing from DSO

### ISSUE THREAD

**Issue by cmakelabs** [lukasvst/dm-vio-ros#21]
While trying to build the ros-wrapper, as noticed that it requires folders and libraries used in [dso](https://github.com/JakobEngel/dso/tree/master/src), like `IOWrapper` and `Sophos`, so I cloned DSO, and copied the required folders and tried also to build the required libraries like Sophos, as I kept getting errors that they are not their, Could you please clarify is that the right way of doing things? Am I going in the way I am supposed to? 

Here for example we can see, how the script main.cpp in dm-vio-ros, uses PangolinDSOViewer, however PangolinDSOViewer first, is not shipped with dm-vio-ros, and second despite that I took it from DSO repo, the one is DSO repo, takes 3 arguments, while the in dm-vio-ros, passes 5. There is clearly a need to have PangolinDSOViewer clearly defined and compatible, may you please comment on that?
![Screenshot from 2024-06-28 18-40-05](https://github.com/lukasvst/dm-vio-ros/assets/153651682/151adfaf-f290-470d-bb34-d651442f55ea)

**Comment by cmakelabs** [comment]
One more, issue, 

```
dm-vio-ros/src/main.cpp: In function ‘void run(dso::IOWrap::PangolinDSOViewer*)’:
/home/dmvio_ws/src/dm-vio-ros/src/main.cpp:201:41: error: ‘class dso::IOWrap::PangolinDSOViewer’ has no member named ‘shouldQuit’
  201 |         if(viewer != nullptr && viewer->shouldQuit())
```

**Comment by lukasvst** [comment]
You don't need to copy anything manually over from DSO, there's a dso folder inside dm-vio which contains all the relevant files. The issue you are getting is because some of the dso files have been changed for dm-vio so they don't match when you copy them over.

**Comment by cmakelabs** [comment]
Thank you, you are right!
