### ISSUE TITLE
OpenGL Error 502: GL_INVALID_OPERATION: The specified operation is not allowed in the current state. In: /usr/local/include/pangolin/gl/gl.hpp, line 214

### ISSUE THREAD

**Issue by vbelkina** [lukasvst/dm-vio-ros#3]
Hello, I am trying to run the euroc rosbag from the notes, however, I receiving the above error and then it does not do anything afterwards. I have seen in other places that usually this error is ignored, so this is why I'm not sure what the problem is. If you have any suggestions, please let me know. I had been able to run dm-vio successfully with my own camera and imu, however, then this error occurred so I wanted to try it with the rosbag. Thank you!

command: 
rosrun dmvio_ros node calib=/home/data/camera.txt settingsFile=/home/dm-vio/configs/euroc.yaml mode=1 nogui=0 preset=1 useimu=1 quiet=1 init_requestFullResetNormalizedErrorThreshold=0.8 init_pgba_skipFirstKFs=1

output: 
Loading settings from yaml file: /home/dm-vio/configs/euroc.yaml!
PHOTOMETRIC MODE WITHOUT CALIBRATION!

=============== PRESET Settings: ===============
DEFAULT settings:
- 1x real-time enforcing
- 2000 active points
- 5-7 active frames
- 1-6 LM iteration each KF
- original image resolution
==============================================
Enabling IMU integration!
QUIET MODE, I'll shut up!
Settings:
accelerometer_noise_density: 0.2
accelerometer_random_walk: 0.003
addVisualToCoarseGraphIfTrackingBad: 0
alwaysCanBreakIMU: 0
baToCoarseAccBiasVariance: 1000
baToCoarseGyrBiasVariance: 0.05
baToCoarsePoseVariance: 0.1
baToCoarseRotVariance: 1
baToCoarseVelVariance: 0.1
calib: /home/data/camera.txt
dynamicWeightRMSEThresh: 8
fixKeyframeDuringCoarseTracking: 1
gamma: 
generalScaleIntervalSize: 60
gravityDirectionFixZ: 1
gyroscope_noise_density: 0.016968
gyroscope_random_walk: 1.9393e-05
imuCalib: 
init_coarseScaleUncertaintyThresh: 1
init_conversionType: 0
init_disableVIOUntilFirstInit: 1
init_fixPoses: 1
init_initDSOParams: 1
init_lambdaLowerBound: 1e-16
init_maxNumPoses: 100
init_multipleBiases: 0
init_multithreadedInitDespiteNonRT: 0
init_onlyKFs: 1
init_pgba_conversionType: 0
init_pgba_delay: 100
init_pgba_prepareGraphAddDelValues: 0
init_pgba_prepareGraphAddFactors: 0
init_pgba_priorExtrinsicsRot: 0.01
init_pgba_priorExtrinsicsTrans: 0.1
init_pgba_priorGravityDirection: 0.4
init_pgba_priorGravityDirectionZ: 0.0001
init_pgba_reinitScaleUncertaintyThresh: 0.5
init_pgba_scaleUncertaintyThresh: 1
init_pgba_skipFirstKFs: 1
init_priorExtrinsicsRot: 0.01
init_priorExtrinsicsTrans: 0.1
init_priorGravityDirection: 0.4
init_priorGravityDirectionZ: 0.0001
init_priorRotSigma: 1e-05
init_priorTransSigma: 1e-05
init_requestFullResetErrorThreshold: -1
init_requestFullResetNormalizedErrorThreshold: 0.8
init_scalePriorAfterInit: 0
init_secondthreshGravdir: 1000
init_secondthreshScale: 1e+07
init_threshGravdir: 1000
init_threshScale: 1.02
init_transitionModel: 2
init_updatePoses: 1
integration_sigma: 0.316227
maxFrameEnergyThreshold: 5000
maxSkipFramesFullReset: -1
maxSkipFramesVisualInertial: 2
maxSkipFramesVisualInit: 0
maxSkipFramesVisualOnlyMode: 1
maxTimeBetweenInitFrames: 100000
minQueueSizeForSkipping: 2
normalizeCamSize: 0
numMeasurementsGravityInit: 40
preload: 1
priorExtrinsicsRot: 0.01
priorExtrinsicsTrans: 0.1
priorGravityDirection: 0.4
priorGravityDirectionZ: 0.0001
resultsPrefix: 
setting_forceNoKFTranslationThresh: 0
setting_maxOptIterations: 6
setting_minFramesBetweenKeyframes: -0.5
setting_minIdepth: 0.02
setting_minOptIterations: 1
setting_optGravity: 1
setting_optIMUExtrinsics: 0
setting_optScaleBA: 1
setting_prior_bias: 0
setting_prior_velocity: 0
setting_scaleFixTH: 0
setting_solverMode: 2048
setting_transferCovToCoarse: 1
setting_visualOnlyAfterScaleFixing: 0
setting_weightDSOCoarse: 0.001
setting_weightDSOToGTSAM: 1.66667e-05
setting_weightZeroPriorDSOInitX: 0
setting_weightZeroPriorDSOInitY: 0
skipFirstKeyframe: 0
skipFramesVisualOnlyDelay: 30
speed: 1
start: 2
transferCovToCoarseMultiplier: 1
updateDynamicWeightDuringOptimization: 1
useScaleDiagonalHack: 0
vignette: 
Reading Calibration from file /home/data/camera.txt ... found!
found RadTan (OpenCV) camera model, building rectifier.
Creating RadTan undistorter
Input resolution: 752 480
In: 458.654000 457.296000 367.215000 248.375000 -0.283408 0.073959 0.000194 0.000018
Out: Rectify Crop
Output resolution: 640 480
finding CROP optimal new model!
initial range: x: -1.0297 - 1.1007; y: -0.6043 - 0.5523!
iteration 00001: range: x: -1.0245 - 1.0952; y: -0.6043 - 0.5523!
iteration 00002: range: x: -1.0194 - 1.0897; y: -0.6043 - 0.5523!
iteration 00003: range: x: -1.0194 - 1.0897; y: -0.6013 - 0.5495!
iteration 00004: range: x: -1.0194 - 1.0897; y: -0.5983 - 0.5468!
iteration 00005: range: x: -1.0194 - 1.0897; y: -0.5983 - 0.5468!

Rectified Kamera Matrix:
302.967       0 308.852
      0 418.335 250.271
      0       0       1

NO PHOTOMETRIC Calibration!
Reading Photometric Calibration from file 
PhotometricUndistorter: Could not open file!
using pyramid levels 0 to 3. coarsest resolution: 80 x 60!
START PANGOLIN!
Switching to initializer state: RealtimeCoarseIMUInitState
PixelSelector: Using block sizes: 16, 16
OpenGL Error 502: GL_INVALID_OPERATION: The specified operation is not allowed in the current state.
In: /usr/local/include/pangolin/gl/gl.hpp, line 214

**Comment by vbelkina** [comment]
I got the euroc rosbag to work -> the problem was with the rostopics. However, I am still having this issue with my own data even though the rostopics match the ones specified. So I suppose there is some other issue that is happening.

**Comment by lukasvst** [comment]
I didn't quite understand the problem you are having. Are you sure that the images and IMU data arrive in the ROS wrapper? Does the GUI work with the EuRoC rosbag?

I don't think the OpenGL Error is the problem but to make sure you can pass `nogui=1` to disable the GUI.

**Comment by vbelkina** [comment]
I ended up explicitly assigning the topics by using /cam0/image_raw:=/camera_topic /imu0:=/imu_topic at the end of the command and that has been working.
