### ISSUE TITLE
suggestion of CMakeLists.txt

### ISSUE THREAD

**Issue by iwander-all** [lukasvst/dm-vio-ros#5]
Hi, it works really good, I have a suggestion that add
`add_dependencies(${PROJECT_NAME}_node ${PROJECT_NAME}_generate_messages_cpp)` at line 85, without which it cannot compile at my computor.

**Comment by lukasvst** [comment]
Thanks a lot for reporting this!
This was indeed a bug (which did not occur on my machine), I'll fix it with the next commit.
